recipes: fix S = "${WORKDIR}" no longer supported on master
uptane/meta-updater pull request #103
Opened 2024-07-01 15:21 UTC by EdTheBearded

On Yocto master (5.1 onwards)  it is no longer supported to use S = "${WORKDIR}". [1]

Following the 5.1 release notes [2], S should now be "${WORKDIR}/sources", and references for ${WORKDIR} in recipe tasks should either be ${UNPACKDIR} or ${S}.

[1] https://git.openembedded.org/openembedded-core/commit/?h=master&id=32cba1cc916ad530c5e6630a927e74ca6f06289b
[2] https://docs.yoctoproject.org/next/qmigration-guides/migration-5.1.html#s-workdir-no-longer-supported

2024-07-04 16:37 UTC, tkfu approved these changes
This LGTM, and seems pretty basic. @EdTheBearded, please wait to merge this until there's input from @ricardosalveti or @detsch, or until 7 days after you submitted the PR, whichever comes first.

(We have an agreed policy to not merge based only on reviews from people within our own respective companies until external folks have had the chance to review it as well. If nobody else picks it up, you can merge it after a week.)

2024-07-04 22:55 UTC, detsch approved these changes
@EdTheBearded  Link [2] in the commit description has a minor typo (an extra 'q'). The right URL is https://docs.yoctoproject.org/next/migration-guides/migration-5.1.html#s-workdir-no-longer-supported

Other than that, LGTM.

@quaresmajose may want to take a look as well.

2024-07-05 11:05 UTC, EdTheBearded commented
Oops! Thanks for letting me know @detsch, already fixed!

2024-07-05 11:17 UTC, quaresmajose requested changes
The change itself LGTM but because it introduces compatibility changes we need to create a scarthgap branch first before this merge.

After this merge we need to also change the LAYERSERIES_COMPAT_sota and so we will be without the scarthgap branch.
 https://github.com/uptane/meta-updater/blob/0aa08f395e2b964a40f3acf374676405db1154b0/conf/layer.conf#L15
```patch
-LAYERSERIES_COMPAT_sota = "nanbield scarthgap" 
+LAYERSERIES_COMPAT_sota = "styhead"
```

2024-07-05 11:53 UTC, EdTheBearded commented
Hey @quaresmajose, should I also include the `LAYERSERIES_COMPAT` change as well, or something that should be done separately, along with the creation of Scarthgap branch?

2024-07-05 12:01 UTC, quaresmajose commented
IMO the LAYERSERIES_COMPAT can be added on this same PR in a new commit, this way it becomes even clearer the incompatibility.

2024-07-05 13:16 UTC, EdTheBearded commented
Sure thing. Already submitted the new commit.

2024-07-16 16:47 UTC, EdTheBearded commented
Do we have the Scarthgap branch created?

2024-07-16 21:40 UTC, ricardosalveti commented
> Do we have the Scarthgap branch created?

Not yet, we should probably create one based on current master as this change is not compatible with it.

2024-07-16 21:41 UTC, ricardosalveti commented
Created https://github.com/uptane/meta-updater/tree/scarthgap.

2024-07-16 21:44 UTC, ricardosalveti approved these changes
LGTM

2024-07-16 21:44 UTC, merged